os:
  - linux
  - osx
language: node_js
node_js:
  - 0.12
  - 4.0
  - 4.1
  - 4.5
  - 5.0
  - 5.5
  - 5.12
  - 6
  - 6.6
install: npm install
after_success:
  - npm run test
  - ./node_modules/.bin/istanbul report text-summary lcov
